### ISSUE TITLE
Works for linear, integer problems?

### ISSUE THREAD

**Issue by matbesancon** [anriseth/MultiJuMP.jl#20]
Does the package work with linear objectives? The examples only use Ipopt as a solver and non-linear problems.

```julia
using MultiJuMP: SingleObjective, MultiModel, getMultiData

const mmodel = MultiModel(solver = ClpSolver())
const y = @variable(mmodel, 0 <= y <= 10.0)
const z = @variable(mmodel, 0 <= z <= 10.0)
@constraint(mmodel, y + z <= 15.0)

# objectives
const exp_obj1 = @expression(mmodel, -y +0.05 * z)
const exp_obj2 = @expression(mmodel, 0.05 * y - z)
const obj1 = SingleObjective(exp_obj1)
const obj2 = SingleObjective(exp_obj2)

# # setting objectives in the data
const multim = getMultiData(mmodel)
multim.objectives = [obj1, obj2]

solve(mmodel)
```

Error:
```
Unexpected object -y + 0.05 z in nonlinear expression.
Stacktrace
```

If it does, a linear / integer example might be interesting. If not, then a note could be added in the README (happy to make a PR in both cases)

**Comment by anriseth** [comment]
The way I set this up back in the day assumes a nonlinear objective. Feel free to submit a PR to the README.

It may not be too difficult to extend it to other types of objectives and constraints, in case anyone would like to do that :)
