### ISSUE TITLE
Basic usage of MultiJuMP

### ISSUE THREAD

**Issue by orhanabar** [anriseth/MultiJuMP.jl#35]
I am planning to start working on multi objective optimization and found MultiJuMP. But the example on the readme page is throwing an error. It looks like it doesn’t recognize the main function of the optimization. Is it working with the newest version of JuMP after they made significant change?

```
using MultiJuMP, JuMP
using Clp: ClpSolver

const mmodel = multi_model(solver = ClpSolver(), linear = true)
const y = @variable(mmodel, 0 <= y <= 10.0)
const z = @variable(mmodel, 0 <= z <= 10.0)
@constraint(mmodel, y + z <= 15.0)

# objectives
const exp_obj1 = @expression(mmodel, -y +0.05 * z)
const exp_obj2 = @expression(mmodel, 0.05 * y - z)
const obj1 = SingleObjective(exp_obj1)
const obj2 = SingleObjective(exp_obj2)

# setting objectives in the data
const multim = get_multidata(mmodel)
multim.objectives = [obj1, obj2]

solve(mmodel, method = WeightedSum())

# Get the Utopia and Nadir points
utopiapoint = getutopia(multim)
nadirpoint = getnadir(multim)
```
Error is :

```
UndefVarError: multi_model not defined

Stacktrace:
 [1] top-level scope at In[38]:3
```

**Comment by matbesancon** [comment]
are you working with Julia 1.0 or greater? If not you might be on a previous version of MultiJuMP

**Comment by orhanabar** [comment]
Yes I am working on julia 1+. However, package is not updated for JuMP v0.19.0. When I downgrade JuMP to 0.18.5 it worked. When do you think you will update for the new release of JuMP?

**Comment by matbesancon** [comment]
we should first check that the features used in MultiJuMP (hooks) are still available in 0.19, if yes then we can adapt the code

**Comment by matbesancon** [comment]
closing this in favour of #37

**Comment by JNSDVD** [comment]
I have exactly the same problem and use exactly the same example. 

Julia1.8.2
downgrade JuMP to 0.18.5 (did not work for me)
MultiJuMP 0.5.0

Are there any ideas what I could do?
