### ISSUE TITLE
Switch to JuMP v0.19

### ISSUE THREAD

**Issue by matbesancon** [anriseth/MultiJuMP.jl#37]
Not sure this is already doable, more of an enhancement. In the meantime, we should freeze JuMP version in Project.toml

**Comment by haydenfree** [comment]
Has there been any progress on updating to support version 0.19 of JuMP? What needs to be done to make this happen? Myself and a few colleagues might be able to assist if necessary.

Thank you!

**Comment by amgad-naiem** [comment]
Should be fixed by #42
