### ISSUE TITLE
Seg fault when running tests

### ISSUE THREAD

**Issue by DrVogt** [anriseth/MultiJuMP.jl#45]
Howdy,

Tried to run the test programs to make sure that everything is good (I have upgraded all my packages)

I keep getting seg faults when running any of the test programs, and it isn't clear why i.e

jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1700 [inlined]
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:369
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:911
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:819
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:769
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:828 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:848
eval at ./boot.jl:331
eval_user_input at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
#26 at ./task.jl:358
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1700 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:687
Allocations: 173746270 (Pool: 173710063; Big: 36207); GC: 195
Segmentation fault: 11

Seems to me like the program is for some reason requesting more threads than available?  Has anybody else encountered this issue/knows the solution?

**Comment by amgad-naiem** [comment]
Hi @DrVogt,

Tests works fine on my end as well as on [travis CI](https://travis-ci.org/github/anriseth/MultiJuMP.jl/builds/771401050). Never had this issue before. Just did `] add MultiJuMP` and `test MultiJuMP` in a fresh latest julia (1.6.1) installation and it worked fine.
